const SAMPLE=[[1779.51,862.31,null],[2094.58,1653.47,null],[34.55,null,null],[442.14,null,294],[141.84,38.23,null],[29778.22,28796.37,null],[197.73,null,158],[67.96,null,27],[66.24,null,22.32],[4.06,null,7.11]];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],tbody=$('#costTable tbody');
const strategy=()=>$('#solverStrategy').value,grid=()=>Number($('#gridSize').value);
function wire(costs,T){return`${T/1e6}\t${strategy()}\t${grid()}\n`+costs.map((r,i)=>[`M${String(i+1).padStart(2,'0')}`,...r.map(v=>v==null?'':v/1e6)].join('\t')).join('\n')}
async function call(path,body){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body}),data=await response.json();if(!response.ok)throw Error(data.error||'SOCI 后端调用失败');return data}
async function sdkEncrypt(costs,T){return(await call('/api/encrypt',wire(costs,T))).rows}
async function sdkOptimize(costs,T,progress){progress('Encrypted B&B 密态搜索',2);const encrypted=await call('/api/optimize',wire(costs,T));progress('PredicateEngine PRUNE / ACCEPT',4);const authorized=await call('/api/workflow/decrypt',encrypted.resultId);progress('生成最终授权结果',5);await new Promise(r=>setTimeout(r,250));let c12=0,c3=0;authorized.solution.forEach((m,i)=>m<3?c12+=costs[i][m-1]:c3+=costs[i][m-1]);return{total:Math.round(authorized.totalCost*1e6),ratio:authorized.ratio,solution:authorized.solution,c12,c3,stats:encrypted.stats,mode:encrypted.mode,strategy:encrypted.strategy,ciphertexts:encrypted.ciphertexts}}
function renderRows(data){tbody.innerHTML='';data.forEach((row,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>M${String(i+1).padStart(2,'0')}</td>`+row.map((v,j)=>`<td><input type="number" min="0" step="0.01" aria-label="物料 ${i+1} 方式 ${j+1}" value="${v??''}" placeholder="不可用" class="${v==null?'unavailable':''}"></td>`).join('');tbody.append(tr)});$$('#costTable input').forEach(x=>x.oninput=()=>x.classList.toggle('unavailable',x.value===''))}
function readMatrix(){return[...tbody.rows].map((r,i)=>[...r.querySelectorAll('input')].map(input=>{if(input.value==='')return null;const v=Number(input.value);if(!Number.isFinite(v)||v<0)throw Error(`物料 ${i+1} 包含非法成本`);return Math.round(v*1e6)}))}
function lexLess(a,b){for(let i=0;i<a.length;i++)if(a[i]!==b[i])return a[i]<b[i];return false}
// Independent exhaustive plaintext oracle. Its node counters are deliberately
// not exposed as confidential statistics.
function solve(costs,T){if(!costs.length)throw Error('至少需要一种物料');const choice=Array(costs.length);let best=null;function dfs(i,total,c12,c3,linear){if(i===costs.length){if(linear<0||c3<=0)return;const candidate={total,c12,c3,ratio:c12/total,solution:[...choice]};if(!best||total<best.total||total===best.total&&(c12<best.c12||c12===best.c12&&lexLess(candidate.solution,best.solution)))best=candidate;return}let available=false;for(let j=0;j<3;j++){const c=costs[i][j];if(c==null)continue;available=true;choice[i]=j+1;j<2?dfs(i+1,total+c,c12+c,c3,linear+(1e6-T)*c):dfs(i+1,total+c,c12,c3+c,linear-T*c)}if(!available)throw Error(`物料 ${i+1} 没有可用方式`)}dfs(0,0,0,0,0);if(!best)throw Error('不存在满足本地化率约束的方案');return best}
function medianSolve(costs,T){const samples=[];let result;for(let round=0;round<7;round++){const start=performance.now();for(let i=0;i<5;i++)result=solve(costs,T);samples.push((performance.now()-start)/5)}samples.sort((a,b)=>a-b);return{result,ms:samples[3]}}
function money(v){return(v/1e6).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function previewPlain(costs){$('#plainPreview').textContent=costs.slice(0,6).map((r,i)=>`M${String(i+1).padStart(2,'0')}  [ ${r.map(v=>v==null?'   null':money(v).padStart(8)).join(' · ')} ]`).join('\n')+(costs.length>6?'\n…':'')}
function previewCipher(rows){$('#cipherPreview').textContent=rows.slice(0,6).map((r,i)=>`M${String(i+1).padStart(2,'0')}  [ ${r.map(v=>v==null?' unavailable ':v.slice(0,22)+'…').join(' · ')} ]`).join('\n')+(rows.length>6?'\n…':'')}
function animateNumber(el,end){el.textContent=Number(end).toLocaleString()}
function showResult(r,T,plainMs,elapsed){$('#resultSection').classList.remove('hidden');const solution=`[${r.solution.join(', ')}]`;$('#plainSolution').textContent=solution;$('#secureSolution').textContent=solution;$('#totalCost').textContent=money(r.total);$('#ratioResult').textContent=(r.ratio*100).toFixed(2)+'%';$('#ratioFill').style.width=(r.ratio*100)+'%';$('#thresholdMarker').style.left=(T/1e4)+'%';$('#overheadResult').textContent=plainMs>0?`≈ ${Math.round(elapsed/plainMs).toLocaleString()}×`:'—';$('#c12Value').textContent=money(r.c12);$('#c3Value').textContent=money(r.c3);$('#formulaTotal').textContent=money(r.total);$('#solutionList').innerHTML=r.solution.map((m,i)=>`<div class="solution-item"><span>物料 M${String(i+1).padStart(2,'0')}</span><b>开发方式 ${m}</b><em>${money(readMatrix()[i][m-1])}</em></div>`).join('');window.lastResult=r}
async function run(){const button=$('#runButton'),plainSteps=$$('[data-plain-step]'),secureSteps=$$('[data-secure-step]');const progress=(label,step)=>{$('#runState').textContent=label;secureSteps.forEach((x,i)=>{x.classList.toggle('active',i===step-1);if(i<step-1)x.classList.add('done')})};try{button.disabled=true;button.classList.add('loading');$('#runState').classList.remove('error');secureSteps.forEach(x=>x.classList.remove('active'));const costs=readMatrix(),T=Math.round(Number($('#threshold').value)*1e6),plain=medianSolve(costs,T);plainSteps.forEach(x=>x.classList.add('done'));progress('Paillier 加密',1);const start=performance.now(),cipherRows=await sdkEncrypt(costs,T);previewPlain(costs);previewCipher(cipherRows);$('#encryptDetail').textContent=`${costs.flat().filter(x=>x!=null).length} 次真实加密`;const result=await sdkOptimize(costs,T,progress),elapsed=performance.now()-start;if(JSON.stringify(result.solution)!==JSON.stringify(plain.result.solution)||result.total!==plain.result.total||result.c12!==plain.result.c12)throw Error('plaintext reference 与 confidential solver 结果不一致');secureSteps.forEach(x=>{x.classList.remove('active');x.classList.add('done')});$('#plainTime').textContent=`${plain.ms.toFixed(3)} ms`;$('#plainPerfNote').textContent='plaintext reference，仅用于一致性验证';$('#secureTime').textContent=`${result.stats.total_seconds.toFixed(3)} s`;$('#securePerfNote').textContent=`pre ${result.stats.preprocessing_seconds.toFixed(3)}s · search ${result.stats.search_seconds.toFixed(3)}s`;for(const [id,key]of[['visitedNodes','visited_nodes'],['prunedNodes','pruned_nodes'],['candidateCount','candidate_count'],['prunePredicates','prune_predicates'],['acceptPredicates','accept_predicates']])animateNumber($('#'+id),result.stats[key]);$('#runtimeMode').textContent=result.mode;$('#activeStrategy').textContent=result.strategy;$('#runState').textContent='结果已核对';showResult(result,T,plain.ms,elapsed)}catch(e){secureSteps.forEach(x=>x.classList.remove('active'));$('#runState').textContent=e.message;$('#runState').classList.add('error')}finally{button.disabled=false;button.classList.remove('loading')}}
fetch('/api/health').then(r=>r.json()).then(x=>{$('#runtimeMode').textContent=x.mode;$$('[data-runtime-mode]').forEach(e=>e.textContent=x.mode)}).catch(()=>$('#runtimeMode').textContent='不可用');
$('#solverStrategy').onchange=e=>$('#gridSize').disabled=e.target.value!=='lagrangian';$('#threshold').oninput=e=>$('#thresholdValue').textContent=Number(e.target.value).toFixed(2);$('#runButton').onclick=run;$('#resetButton').onclick=()=>renderRows(SAMPLE);$('#addRowButton').onclick=()=>renderRows([...readMatrix().map(r=>r.map(v=>v==null?null:v/1e6)),[null,null,null]]);$('#themeButton').onclick=()=>document.body.classList.toggle('dark');$('#copyButton').onclick=async()=>{const r=window.lastResult;if(r)await navigator.clipboard.writeText(JSON.stringify({total_cost:r.total/1e6,ratio:r.ratio,solution:r.solution},null,2))};renderRows(SAMPLE);
