const SAMPLE=[[1779.51,862.31,null],[2094.58,1653.47,null],[34.55,null,null],[442.14,null,294],[141.84,38.23,null],[29778.22,28796.37,null],[197.73,null,158],[67.96,null,27],[66.24,null,22.32],[4.06,null,7.11]];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const tbody=$('#costTable tbody'), delay=ms=>new Promise(r=>setTimeout(r,ms));
function wire(costs,T){return `${T/1e6}\n`+costs.map((r,i)=>[`M${String(i+1).padStart(2,'0')}`,...r.map(v=>v==null?'':v/1e6)].join('\t')).join('\n')}
async function sdkOptimize(costs,T,progress=()=>{}){progress('正在执行密态优化',2);const response=await fetch('/api/optimize',{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:wire(costs,T)}),encrypted=await response.json();if(!response.ok)throw Error(encrypted.error||'加密计算失败');progress('正在授权读取结果',4);const reveal=await fetch('/api/workflow/decrypt',{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:encrypted.ciphertexts.join('\n')}),data=await reveal.json();if(!reveal.ok)throw Error(data.error||'结果授权解密失败');let c12=0,c3=0;data.solution.forEach((m,i)=>{if(m<3)c12+=costs[i][m-1];else c3+=costs[i][m-1]});return{total:Math.round(data.totalCost*1e6),ratio:data.ratio,solution:data.solution,c12,c3,visited:0,pruned:0,feasible:0}}
async function sdkEncrypt(costs,T){const response=await fetch('/api/encrypt',{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:wire(costs,T)}),data=await response.json();if(!response.ok)throw Error(data.error||'SOCI 加密失败');return data.rows}

function renderRows(data){tbody.innerHTML='';data.forEach((row,i)=>{const tr=document.createElement('tr');tr.innerHTML=`<td>M${String(i+1).padStart(2,'0')}</td>`+row.map((v,j)=>`<td><input type="number" min="0" step="0.01" aria-label="物料 ${i+1} 方式 ${j+1}" value="${v??''}" placeholder="不可用" class="${v==null?'unavailable':''}"></td>`).join('');tbody.append(tr)});bindInputs()}
function bindInputs(){$$('#costTable input').forEach(input=>input.addEventListener('input',()=>input.classList.toggle('unavailable',input.value==='')))}
function readMatrix(){return [...tbody.rows].map((r,i)=>[...r.querySelectorAll('input')].map(input=>{if(input.value==='')return null;const v=Number(input.value);if(!Number.isFinite(v)||v<0)throw new Error(`物料 ${i+1} 包含非法成本`);return Math.round(v*1e6)}))}
function lexLess(a,b){for(let i=0;i<a.length;i++){if(a[i]!==b[i])return a[i]<b[i]}return false}
function solve(costs,T){if(!costs.length)throw new Error('至少需要一种物料');costs.forEach((r,i)=>{if(r.every(v=>v==null))throw new Error(`物料 ${i+1} 没有可用方式`)});const n=costs.length,S=1e6,minSuffix=Array(n+1).fill(0),maxRatio=Array(n+1).fill(0);for(let i=n-1;i>=0;i--){const available=costs[i].filter(v=>v!=null);minSuffix[i]=minSuffix[i+1]+Math.min(...available);maxRatio[i]=maxRatio[i+1]+Math.max(...costs[i].map((c,j)=>c==null?-Infinity:j<2?(S-T)*c:-T*c))}let best=null,visited=0,pruned=0,feasible=0;const choice=Array(n);function dfs(i,total,c12,c3,linear){visited++;if(best&&total+minSuffix[i]>best.total){pruned++;return}if(linear+maxRatio[i]<0){pruned++;return}if(i===n){if(linear<0||c3<=0||total<=0)return;feasible++;const ratio=c12/total,gap=ratio-T/S,candidate={total,c12,c3,ratio,solution:[...choice]};if(!best||total<best.total||(total===best.total&&(gap<best.ratio-T/S-1e-15||(Math.abs(gap-(best.ratio-T/S))<1e-15&&lexLess(candidate.solution,best.solution)))))best=candidate;return}for(let j=0;j<3;j++){const c=costs[i][j];if(c==null)continue;choice[i]=j+1;j<2?dfs(i+1,total+c,c12+c,c3,linear+(S-T)*c):dfs(i+1,total+c,c12,c3+c,linear-T*c)}}dfs(0,0,0,0,0);if(!best)throw new Error('不存在满足本地化率约束的方案');return{...best,visited,pruned,feasible}}
function money(v){return (v/1e6).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}
function fakeCipher(index){return `0x${Array.from({length:15},(_,i)=>((index*37+i*19+11)%16).toString(16)).join('')}…`}
function previewPlain(costs){$('#plainPreview').textContent=costs.slice(0,6).map((r,i)=>`M${String(i+1).padStart(2,'0')}  [ ${r.map(v=>v==null?'   null':money(v).padStart(8)).join(' · ')} ]`).join('\n')+(costs.length>6?'\n…':'' )}
function previewCipher(rows){$('#cipherPreview').textContent=rows.slice(0,6).map((r,i)=>`M${String(i+1).padStart(2,'0')}  [ ${r.map(v=>v==null?' unavailable ':v.slice(0,22)+'…').join(' · ')} ]`).join('\n')+(rows.length>6?'\n…':'' )}
function medianSolve(costs,T){const samples=[];let result;for(let round=0;round<31;round++){const start=performance.now();for(let i=0;i<20;i++)result=solve(costs,T);samples.push((performance.now()-start)/20)}samples.sort((a,b)=>a-b);return{result,ms:samples[15]}}
function secureEstimate(valid){const encryptOps=valid+3,ms=encryptOps*26.929443+80.362698+163.979595+3*26.832080;return{ms,encryptOps}}
async function animate(result,costs,T,plainMs,secure,cipherRows){const plainSteps=$$('[data-plain-step]'),secureSteps=$$('[data-secure-step]');previewPlain(costs);previewCipher(cipherRows);plainSteps.forEach(x=>x.classList.add('done'));secureSteps.forEach(x=>{x.classList.remove('active');x.classList.add('done')});$('#plainTime').textContent=plainMs<.01?'< 0.01 ms':`${plainMs.toFixed(3)} ms`;$('#plainPerfNote').textContent='31 轮 × 20 次求解的中位单次耗时';$('#secureTime').textContent=`${(secure.ms/1000).toFixed(2)} s`;$('#securePerfNote').textContent='加密计算端到端耗时';animateNumber($('#visitedNodes'),result.visited);animateNumber($('#prunedNodes'),result.pruned);animateNumber($('#candidateCount'),result.feasible);animateNumber($('#encryptedCells'),costs.flat().filter(x=>x!=null).length);$('#runState').textContent='结果已核对';showResult(result,T,plainMs,secure.ms)}
function animateNumber(el,end){let start=0;const timer=setInterval(()=>{start=Math.min(end,start+Math.max(1,Math.ceil(end/18)));el.textContent=start.toLocaleString();if(start===end)clearInterval(timer)},25)}
function showResult(r,T,plainMs,secureMs){$('#resultSection').classList.remove('hidden');const solution=`[${r.solution.join(', ')}]`;$('#plainSolution').textContent=solution;$('#secureSolution').textContent=solution;$('#totalCost').textContent=money(r.total);$('#ratioResult').textContent=(r.ratio*100).toFixed(2)+'%';$('#ratioFill').style.width=(r.ratio*100)+'%';$('#thresholdMarker').style.left=(T/1e4)+'%';$('#overheadResult').textContent=plainMs>0?`≈ ${Math.round(secureMs/plainMs).toLocaleString()}×`:'—';$('#c12Value').textContent=money(r.c12);$('#c3Value').textContent=money(r.c3);$('#formulaTotal').textContent=money(r.total);$('#solutionList').innerHTML=r.solution.map((m,i)=>`<div class="solution-item"><span>物料 M${String(i+1).padStart(2,'0')}</span><b>开发方式 ${m}</b><em>${money(readMatrix()[i][m-1])}</em></div>`).join('');$('#resultSection').scrollIntoView({behavior:'smooth',block:'start'});window.lastResult=r}
async function run(){const button=$('#runButton'),plainSteps=$$('[data-plain-step]'),secureSteps=$$('[data-secure-step]');const progress=(text,step)=>{$('#runState').textContent=text;secureSteps.forEach((el,i)=>{el.classList.toggle('active',i===step-1);if(i<step-1)el.classList.add('done')})};try{button.disabled=true;button.classList.add('loading');button.querySelector('span').textContent='正在计算…';$('#runState').classList.remove('error');$('#runState').textContent='正在准备数据';[...plainSteps,...secureSteps].forEach(x=>x.classList.remove('active','done'));$('#resultSection').classList.add('hidden');await new Promise(requestAnimationFrame);const costs=readMatrix(),T=Math.round(Number($('#threshold').value)*1e6);plainSteps[0].classList.add('active');await new Promise(requestAnimationFrame);const measured=medianSolve(costs,T);plainSteps.forEach(x=>{x.classList.remove('active');x.classList.add('done')});progress('正在加密数据',1);const start=performance.now(),cipherRows=await sdkEncrypt(costs,T);previewCipher(cipherRows);$('#encryptDetail').textContent=`${costs.flat().filter(x=>x!=null).length} 次加密运算`;const result=await sdkOptimize(costs,T,progress),secure={ms:performance.now()-start,encryptOps:costs.flat().filter(x=>x!=null).length};if(JSON.stringify(result.solution)!==JSON.stringify(measured.result.solution))throw Error('浏览器参考结果与计算结果不一致');await animate(result,costs,T,measured.ms,secure,cipherRows)}catch(e){$('#runState').textContent=e.message;$('#runState').classList.add('error')}finally{button.disabled=false;button.classList.remove('loading');button.querySelector('span').textContent='同时运行两条路径'}}
$('#threshold').addEventListener('input',e=>$('#thresholdValue').textContent=Number(e.target.value).toFixed(2));$('#runButton').addEventListener('click',run);$('#resetButton').addEventListener('click',()=>{renderRows(SAMPLE);$('#threshold').value=.5;$('#thresholdValue').textContent='0.50';$('#resultSection').classList.add('hidden')});$('#addRowButton').addEventListener('click',()=>renderRows([...readMatrix().map(r=>r.map(v=>v==null?null:v/1e6)),[null,null,null]]));$('#themeButton').addEventListener('click',()=>document.body.classList.toggle('dark'));$('#copyButton').addEventListener('click',async()=>{const r=window.lastResult;if(!r)return;await navigator.clipboard.writeText(JSON.stringify({total_cost:r.total/1e6,ratio:r.ratio,solution:r.solution},null,2));$('#copyButton').textContent='已复制';setTimeout(()=>$('#copyButton').textContent='复制结果',1200)});renderRows(SAMPLE);
