#include <jni.h>
#include "soci/soci.h"
#include <string>
#include <vector>
static void fail(JNIEnv*e,const char*m){jclass c=e->FindClass("com/soci/sdk/SociException");e->ThrowNew(c,m);}
extern "C" JNIEXPORT jlong JNICALL Java_com_soci_sdk_SociRuntime_nativeCreate(JNIEnv*e,jclass,jstring d){const char*s=e->GetStringUTFChars(d,nullptr);soci_runtime_t*r=nullptr;auto rc=soci_runtime_create(s,&r);e->ReleaseStringUTFChars(d,s);if(rc){fail(e,"runtime create failed");return 0;}return (jlong)r;}
extern "C" JNIEXPORT void JNICALL Java_com_soci_sdk_SociRuntime_nativeClose(JNIEnv*,jclass,jlong h){soci_runtime_close((soci_runtime_t*)h);}
extern "C" JNIEXPORT void JNICALL Java_com_soci_sdk_SociRuntime_nativeCreateKey(JNIEnv*e,jclass,jlong h,jstring id,jint bits){const char*s=e->GetStringUTFChars(id,nullptr);auto rc=soci_create_key((soci_runtime_t*)h,s,bits,SOCI_ROLE_FULL);e->ReleaseStringUTFChars(id,s);if(rc)fail(e,soci_runtime_get_last_error((soci_runtime_t*)h));}
extern "C" JNIEXPORT jstring JNICALL Java_com_soci_sdk_SociRuntime_nativeDecrypt(JNIEnv*e,jclass,jlong h,jbyteArray a){jsize l=e->GetArrayLength(a);std::string b(l,0);e->GetByteArrayRegion(a,0,l,(jbyte*)b.data());size_t n=0;soci_decrypt((soci_runtime_t*)h,(uint8_t*)b.data(),l,nullptr,&n);std::string o(n,0);auto rc=soci_decrypt((soci_runtime_t*)h,(uint8_t*)b.data(),l,o.data(),&n);if(rc){fail(e,soci_runtime_get_last_error((soci_runtime_t*)h));return nullptr;}return e->NewStringUTF(o.c_str());}
static std::vector<uint8_t> bytes(JNIEnv*e,jbyteArray a){std::vector<uint8_t>b(e->GetArrayLength(a));e->GetByteArrayRegion(a,0,b.size(),(jbyte*)b.data());return b;}
static jbyteArray array(JNIEnv*e,const std::vector<uint8_t>&b){auto a=e->NewByteArray(b.size());e->SetByteArrayRegion(a,0,b.size(),(const jbyte*)b.data());return a;}
template<class F>static jbyteArray output(JNIEnv*e,soci_runtime_t*h,F f){size_t n=0;auto rc=f(nullptr,&n);if(rc!=SOCI_BUFFER_TOO_SMALL){fail(e,soci_runtime_get_last_error(h));return nullptr;}for(int i=0;i<3;i++){std::vector<uint8_t>o(n);rc=f(o.data(),&n);if(rc==SOCI_OK){o.resize(n);return array(e,o);}if(rc!=SOCI_BUFFER_TOO_SMALL){fail(e,soci_runtime_get_last_error(h));return nullptr;}}fail(e,"output size changed repeatedly");return nullptr;}
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_soci_sdk_SociRuntime_nativeEncrypt(JNIEnv*e,jclass,jlong x,jstring m){auto*h=(soci_runtime_t*)x;const char*s=e->GetStringUTFChars(m,nullptr);auto r=output(e,h,[&](uint8_t*o,size_t*n){return soci_encrypt(h,s,o,n);});e->ReleaseStringUTFChars(m,s);return r;}
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_soci_sdk_SociRuntime_nativeBinary(JNIEnv*e,jclass,jlong x,jint op,jbyteArray aa,jbyteArray ab){auto*h=(soci_runtime_t*)x;auto a=bytes(e,aa),b=bytes(e,ab);return output(e,h,[&](uint8_t*o,size_t*n){if(op==0)return soci_add(h,a.data(),a.size(),b.data(),b.size(),o,n);if(op==1)return soci_secure_mul(h,a.data(),a.size(),b.data(),b.size(),o,n);return soci_secure_compare(h,a.data(),a.size(),b.data(),b.size(),o,n);});}
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_soci_sdk_SociRuntime_nativeUnary(JNIEnv*e,jclass,jlong x,jint op,jbyteArray aa){auto*h=(soci_runtime_t*)x;auto a=bytes(e,aa);return output(e,h,[&](uint8_t*o,size_t*n){return op?soci_secure_abs(h,a.data(),a.size(),o,n):soci_secure_sign_bit(h,a.data(),a.size(),o,n);});}
extern "C" JNIEXPORT jbyteArray JNICALL Java_com_soci_sdk_SociRuntime_nativeScalarMul(JNIEnv*e,jclass,jlong x,jbyteArray aa,jstring kk){auto*h=(soci_runtime_t*)x;auto a=bytes(e,aa);const char*k=e->GetStringUTFChars(kk,nullptr);auto r=output(e,h,[&](uint8_t*o,size_t*n){return soci_scalar_mul(h,a.data(),a.size(),k,o,n);});e->ReleaseStringUTFChars(kk,k);return r;}
extern "C" JNIEXPORT jobjectArray JNICALL Java_com_soci_sdk_SociRuntime_nativeDiv(JNIEnv*e,jclass,jlong x,jbyteArray aa,jbyteArray ab){auto*h=(soci_runtime_t*)x;auto a=bytes(e,aa),b=bytes(e,ab);size_t qn=0,rn=0;auto rc=soci_secure_div(h,a.data(),a.size(),b.data(),b.size(),nullptr,&qn,nullptr,&rn);if(rc!=SOCI_BUFFER_TOO_SMALL){fail(e,soci_runtime_get_last_error(h));return nullptr;}std::vector<uint8_t>q(qn),r(rn);rc=soci_secure_div(h,a.data(),a.size(),b.data(),b.size(),q.data(),&qn,r.data(),&rn);if(rc){fail(e,soci_runtime_get_last_error(h));return nullptr;}jclass bc=e->FindClass("[B");jobjectArray out=e->NewObjectArray(2,bc,nullptr);e->SetObjectArrayElement(out,0,array(e,q));e->SetObjectArrayElement(out,1,array(e,r));return out;}
